from __future__ import annotations

# compatibility facade: keep existing imports stable while logic lives in focused modules.
from .store_boxes import (
    create_detection_run,
    delete_boxes_by_ids,
    get_box_text_by_id,
    replace_boxes_for_type,
    set_box_ocr_text_by_id,
    set_box_order_for_type,
    set_box_translation_by_id,
    update_box_geometry_by_id,
)
from .store_context import (
    clear_page_context_snapshot,
    clear_volume_context,
    get_page_context_snapshot,
    get_volume_context,
    upsert_page_context,
    upsert_volume_context,
)
from .store_volume_page import (
    create_volume,
    delete_page,
    delete_volume,
    ensure_page,
    get_max_page_index,
    get_page_context,
    get_page_index,
    get_volume,
    list_page_filenames,
    list_pages,
    list_volumes,
    load_page,
    save_page,
    set_page_context,
    update_volume_next_index,
    volume_name_exists,
)
from .store_volume_reset import clear_volume_derived_data

__all__ = [
    "clear_page_context_snapshot",
    "clear_volume_context",
    "clear_volume_derived_data",
    "create_detection_run",
    "create_volume",
    "delete_boxes_by_ids",
    "delete_page",
    "delete_volume",
    "ensure_page",
    "get_box_text_by_id",
    "get_max_page_index",
    "get_page_context",
    "get_page_context_snapshot",
    "get_page_index",
    "get_volume",
    "get_volume_context",
    "list_page_filenames",
    "list_pages",
    "list_volumes",
    "load_page",
    "replace_boxes_for_type",
    "save_page",
    "set_box_ocr_text_by_id",
    "set_box_order_for_type",
    "set_box_translation_by_id",
    "set_page_context",
    "update_box_geometry_by_id",
    "update_volume_next_index",
    "upsert_page_context",
    "upsert_volume_context",
    "volume_name_exists",
]
